services:
  caddy:
    image: caddy:2
    container_name: caddy
    restart: always

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./Caddyfile.prod:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

    depends_on:
      - osticket

  osticket:
    image: ghcr.io/YOUR_GITHUB_USERNAME/YOUR_REPO/osticket:latest
    container_name: osticket-app
    restart: always

    env_file:
      - .env

    environment:
      APP_ENV: production
      TZ: UTC
      DB_HOST: db
      DB_PORT: 3306

    expose:
      - "80"

    #Uncomment after the installation
    #volumes:
    #  - - /opt/osticket/ost-config.php:/var/www/html/include/ost-config.php:ro

    depends_on:
      - db

  db:
    image: mariadb:11.4
    container_name: osticket-db
    restart: always

    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}

    ports:
      - "127.0.0.1:3306:3306"

    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  caddy_data:
  caddy_config:
  mariadb_data: